### PR TITLE
Set up for MyBinder

### PR DESCRIPTION
**Pull request by robertodr**

### CODE REVIEW

**Review by wikfeldt — APPROVED** [review]
perfect, thanks. PR for main info in readme coming

**Comment by wikfeldt** [comment]
seems that some repo2docker test fails.

The readme update will also conflict with my PR, let me know if I should pull your changes or if you'll pull mine

**Comment by robertodr** [comment]
Yes, the action is missing the secrets for uploading the Docker image. I am working on it.

**Comment by robertodr** [comment]
Docker!!! :angry:

**Pull request merged**
